export const SEARCH_ALL_PRODUCTS_START = "SEARCH_ALL_PRODUCTS_START";
export const SEARCH_ALL_PRODUCTS_ERROR = "SEARCH_ALL_PRODUCTS_ERROR";
export const SEARCH_ALL_PRODUCTS_COMPLETE = "SEARCH_ALL_PRODUCTS_COMPLETE";
export const SEARCH_BURGER_PRODUCTS_START = "SEARCH_BURGER_PRODUCTS_START";
export const SEARCH_BURGER_PRODUCTS_ERROR = "SEARCH_BURGER_PRODUCTS_ERROR";
export const SEARCH_BURGER_PRODUCTS_COMPLETE =
  "SEARCH_BURGER_PRODUCTS_COMPLETE";
export const SEARCH_PIZZA_PRODUCTS_START = "SEARCH_PIZZA_PRODUCTS_START";
export const SEARCH_PIZZA_PRODUCTS_ERROR = "SEARCH_PIZZA_PRODUCTS_ERROR";
export const SEARCH_PIZZA_PRODUCTS_COMPLETE = "SEARCH_PIZZA_PRODUCTS_COMPLETE";
export const SEARCH_HOTDOG_PRODUCTS_START = "SEARCH_HOTDOG_PRODUCTS_START";
export const SEARCH_HOTDOG_PRODUCTS_ERROR = "SEARCH_HOTDOG_PRODUCTS_ERROR";
export const SEARCH_HOTDOG_PRODUCTS_COMPLETE =
  "SEARCH_HOTDOG_PRODUCTS_COMPLETE";
export const SEARCH_DRINKS_PRODUCTS_START = "SEARCH_DRINKS_PRODUCTS_START";
export const SEARCH_DRINKS_PRODUCTS_ERROR = "SEARCH_DRINKS_PRODUCTS_ERROR";
export const SEARCH_DRINKS_PRODUCTS_COMPLETE =
  "SEARCH_DRINKS_PRODUCTS_COMPLETE";
export const SEARCH_PRODUCT_BY_ID_START = "SEARCH_PRODUCT_BY_ID_START";
export const SEARCH_PRODUCT_BY_ID_ERROR = "SEARCH_PRODUCT_BY_ID_ERROR";
export const SEARCH_PRODUCT_BY_ID_COMPLETE = "SEARCH_PRODUCT_BY_ID_COMPLETE";
